### ISSUE TITLE
Add election manager logging ballot preparation & modification per 5.4.1

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxmail#126]
Pro V&V identified a gap in the election manager logging process when ballots are prepared and modified by election officials. We need to satisfy the following requirements in VVSG 5.4.1:

5.4.1 Pre-election Audit Records
During election definition and ballot preparation, the system shall audit the preparation of the
baseline ballot formats and modifications to them, a description of these modifications, and
corresponding dates.

The log shall include:
a. The allowable number of selections a contest
b.The combinations of voting patterns permitted or required by the jurisdiction
c. The inclusion or exclusion of contests as the result of multiple districting within the
polling place
d. Any other characteristics that may be peculiar to the jurisdiction, the election or the
polling place location
e. Manual data maintained by election personnel
f. Samples of all final ballot formats
g. Ballot preparation edit listings

**Comment by mcchilders** [comment]
@carolinemodic  how does this dovetail/not with the other work you're doing?

**Comment by carolinemodic** [comment]
@mcchilders Yeah I think this is encompassed by the work in https://zube.io/votingworks/vxsuite/c/3516 although I think the VVSG rule here might be from 1.0 or 1.1 instead of 2.0 which I'm basing the work in that other ticket off of. So if we want to make sure to support this specific 1.1 rule then let me know. 2.0 does still require logging when modifications are made to the ballot formats but the exact text might be a bit different.

**Comment by mcchilders** [comment]
Ah, perfect @carolinemodic , then I am going to archive this.
