### ISSUE TITLE
either-neither measure mechanism

### ISSUE THREAD

**Issue by benadida** [votingworks/vxmail#145]
as per https://ballotpedia.org/Mississippi_Initiative_65_and_Alternative_65A,_Medical_Marijuana_Amendment_(2020)

Possible implementations:
- a new type of question altogether
- two normal candidate questions, with a special way to parse the CVRs to remove the invalid combinations.
- something else?

**Comment by mattroe** [comment]
Here's the example 2015 ballot measure in the format we need to support [ms_2015_either_neither_measure.pdf](https://zube.io/files/votingworks/1d570315f3a1ac96bd07bf9be1056023-ms_2015_either_neither_measure.pdf)

**Comment by mcchilders** [comment]
The code section showing what this has to look like is here: 
Universal Citation: MS Code § 23-17-37 (2019)
If an initiative measure proposed to the Legislature has been rejected by the Legislature and an alternative measure is passed by the Legislature in lieu thereof, the serial numbers and ballot titles of both such measures shall be printed on the official ballots so that a voter can express separately two (2) preferences: First, by voting for the approval of either measure or against both measures, and, secondly, by voting for one measure or the other measure. If the majority of those voting on the first issue is against both measures, then both measures fail, but in that case the votes on the second issue nevertheless shall be carefully counted and made public. If a majority voting on the first issue is for the approval of either measure, then the measure receiving a majority of the votes on the second issue and also receiving not less than forty percent (40%) of the total votes cast at the election at which the measure was submitted for approval shall be law. Any person who votes against both measures on the first issue may vote but shall not be required to vote for any of the measures on the second issue in order for the ballot to be valid. Substantially the following form shall be a compliance with this section:

INITIATED BY PETITION AND ALTERNATIVE BY LEGISLATURE
 Initiative Measure No. ________, entitled (here insert the ballot title of the initiative measure).
 Alternative Measure No. ________ A, entitled (here insert the ballot title of the alternative measure).
 
VOTE FOR APPROVAL OF EITHER, OR AGAINST BOTH:
 
FOR APPROVAL OF EITHER Initiative No. ________ OR Alternative No. ________ A .......................................( )
 AGAINST BOTH initiative No. ________ AND Alternative No. ________ A ......................................( )
 
AND VOTE FOR ONE:

FOR Initiative Measure No. ________ .................................( )
FOR Alternative Measure No. ________ A ..............................( )

**Comment by benadida** [comment]
we've got SEMS files and looking at how to extract either-or data from there.

**Comment by benadida** [comment]
ballot-encoder updated to support new data model.
